namespace FrostyStarsCompanion.Web.Model.Stargrave
{
    public enum Background
    {
        Biomorph,
        Cyborg,
        Mystic,
        RoboticsExpert,
        Rogue,
        Psionicist,
        Tekker,
        Veteran
    }
    
    public enum Powers
    {
        AdrenalineSurge,
        ArmourPlates,
        Camouflage,
        Fling,
        Regenerate,
        RestructureBody,
        ToxicClaws,
        ToxicSecretion,
        ControlRobot,
        DataKnock,
        EnergyShield,
        PowerSpike,
        QuickStep,
        TargetLock,
        TemporaryUpgrade,
        ControlAnimal,
        DarkEnergy,
        Heal,
        LifeLeach,
        MysticTrance,
        PuppetMaster,
        Suggestion,
        VoidBlade,
        CreateRobot,
        Drone,
        ElectromagneticPulse,
        RemoteFiring,
        RemoteGuidance,
        RepairRobot,
        RewireRobot,
        BaitAndSwitch,
        Bribe,
        CancelPower,
        ConcealedFirearm,
        DataJump,
        Fortune,
        Haggle,
        BreakLock,
        DestroyWeapon,
        Lift,
        PsionicFire,
        PsychicShield,
        Pull,
        WallOfForce,
        AntigravityProjection,
        DataSkip,
        HolographicWall,
        Transport,
        Armoury,
        Command,
        CoordinatedFire,
        TargetDesignation
    }

    public enum Category
    {
        SelfOnly,
        OutOfGameAfter,
        OutOfGameBefore,
        Touch,
        LineOfSight,
        Heal
    }
}